name: Auto-Merge Dependabot PRs

run-name: Auto-Merge PR #${{ github.event.pull_request.number }}

on:
  pull_request:

jobs:
  automerge:
    uses: alexdlaird/.github/.github/workflows/automerge.yml@main
    permissions:
      contents: write
      pull-requests: write
