name: Auto-Merge Dependabot PRs

on:
  pull_request:

jobs:
  automerge:
    uses: alexdlaird/.github/.github/workflows/automerge.yml@main
    permissions:
      contents: write
      pull-requests: write
