name: "Label Commenter"

run-name: Label Commenter #${{ github.event.issue.number || github.event.pull_request.number }}

on:
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled

jobs:
  label-commenter:
    uses: alexdlaird/.github/.github/workflows/label-commenter.yml@main
    permissions:
      issues: write
      pull-requests: write
