name: "Label Commenter"

on:
  issues:
    types:
      - labeled

jobs:
  label-commenter:
    uses: alexdlaird/.github/.github/workflows/label-commenter.yml@main
    permissions:
      issues: write
      pull-requests: write
